/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taxiapp;

import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class BookRide extends javax.swing.JFrame {

    /**
     * Creates new form BookRide
     */
    public BookRide() {
        initComponents();
        myInitComponents();
    }
    
    private void myInitComponents(){
        //        Set Icon Image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        
//        Get random index
        int i = calculation.getNum();
//        Set label for wait time
        waitTime.setText(calculation.getWaitTime()+ " mins Away");
//        Set Destination text
        destinationLabel.setText(calculation.getLocation(1));
       
        java.util.Dictionary driver = calculation.getDriver(i);
        driverName.setText(driver.get("name").toString());
        car.setText(driver.get("car").toString() + " - "+ driver.get("color").toString());
        contact.setText(driver.get("contact").toString());
        price.setText("N "+driver.get("price").toString());
        
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override   
            public void run() {
                new Driving().setVisible(true);
                setVisible(false);
            }
        }, 7000L);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        waitTime = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        driverName = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        waitTime.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        waitTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waitTime.setText("1 mins Away");

        destinationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        destinationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destinationLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\marker (2).png")); // NOI18N
        destinationLabel.setText("Destination Location");

        driverName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverName.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\user-free-icon-font.png")); // NOI18N
        driverName.setText("DRIVER NAME");

        car.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        car.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\taxi-free-icon-font.png")); // NOI18N
        car.setText("Car Model - Color");

        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\phone-call-free-icon-font.png")); // NOI18N
        contact.setText("Contact Number");

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("N Price");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\cross-circle-free-icon-font (1).png")); // NOI18N
        jButton1.setText("Cancel Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driverName)
                            .addComponent(contact)
                            .addComponent(car)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinationLabel)
                            .addComponent(waitTime))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(waitTime, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(destinationLabel)
                .addGap(33, 33, 33)
                .addComponent(driverName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contact)
                .addGap(18, 18, 18)
                .addComponent(car)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        new TaxiApp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRide().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel driverName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel price;
    private javax.swing.JLabel waitTime;
    // End of variables declaration//GEN-END:variables
}
