/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taxiapp;

import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class Driving extends javax.swing.JFrame {

    /**
     * Creates new form Driving
     */
    public Driving() {
        initComponents();
        myInitComponents();
    }
    
    public void myInitComponents(){
        //        Get random index
        int i = calculation.getNum();
        
        tripDuration.setText(calculation.getTripTime() + " MINS");
        pickupLocation.setText(calculation.getLocation(0));
        dropLocation.setText(calculation.getLocation(1));
        
        java.util.Dictionary driver = calculation.getDriver(i);
        tripFare.setText("N "+driver.get("price").toString());
        
        //        Set Icon Image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tripDuration = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pickupLocation = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dropLocation = new javax.swing.JLabel();
        tripFare = new javax.swing.JLabel();
        share = new javax.swing.JLabel();
        finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tripDuration.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tripDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripDuration.setText("20 MINS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driving to destination");

        pickupLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pickupLocation.setText("Pick up location");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\marker (2).png")); // NOI18N

        dropLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dropLocation.setText("Drop off location");

        tripFare.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tripFare.setText("N Fare");

        share.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        share.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\share-free-icon-font.png")); // NOI18N
        share.setText("Share ride details");

        finish.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\cross-circle-free-icon-font (2).png")); // NOI18N
        finish.setText("End trip");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(share)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(finish))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tripDuration)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(tripFare))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(jLabel2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(pickupLocation)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(dropLocation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tripDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pickupLocation)
                    .addComponent(jLabel4)
                    .addComponent(dropLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(share)
                    .addComponent(tripFare)
                    .addComponent(finish))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        new Finished().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driving().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dropLocation;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel pickupLocation;
    private javax.swing.JLabel share;
    private javax.swing.JLabel tripDuration;
    private javax.swing.JLabel tripFare;
    // End of variables declaration//GEN-END:variables
}
