/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taxiapp;

import java.awt.Toolkit;

/**
 *
 * @author USER
 */
public class Finished extends javax.swing.JFrame {

    /**
     * Creates new form Finished
     */
    public Finished() {
        initComponents();
        myInitComponents();
    }
    
    public void myInitComponents(){
    //        Set Icon Image
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        star1 = new javax.swing.JCheckBox();
        star2 = new javax.swing.JCheckBox();
        star3 = new javax.swing.JCheckBox();
        star4 = new javax.swing.JCheckBox();
        star5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        star1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font.png")); // NOI18N
        star1.setMaximumSize(new java.awt.Dimension(30, 30));
        star1.setMinimumSize(new java.awt.Dimension(30, 30));
        star1.setPreferredSize(new java.awt.Dimension(30, 30));
        star1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font (1).png")); // NOI18N
        star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star1ActionPerformed(evt);
            }
        });

        star2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font.png")); // NOI18N
        star2.setMaximumSize(new java.awt.Dimension(30, 30));
        star2.setMinimumSize(new java.awt.Dimension(30, 30));
        star2.setPreferredSize(new java.awt.Dimension(30, 30));
        star2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font (1).png")); // NOI18N
        star2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star2ActionPerformed(evt);
            }
        });

        star3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font.png")); // NOI18N
        star3.setMaximumSize(new java.awt.Dimension(30, 30));
        star3.setMinimumSize(new java.awt.Dimension(30, 30));
        star3.setPreferredSize(new java.awt.Dimension(30, 30));
        star3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font (1).png")); // NOI18N
        star3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star3ActionPerformed(evt);
            }
        });

        star4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font.png")); // NOI18N
        star4.setMaximumSize(new java.awt.Dimension(30, 30));
        star4.setMinimumSize(new java.awt.Dimension(30, 30));
        star4.setPreferredSize(new java.awt.Dimension(30, 30));
        star4.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font (1).png")); // NOI18N
        star4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star4ActionPerformed(evt);
            }
        });

        star5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        star5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font.png")); // NOI18N
        star5.setMaximumSize(new java.awt.Dimension(30, 30));
        star5.setMinimumSize(new java.awt.Dimension(30, 30));
        star5.setPreferredSize(new java.awt.Dimension(30, 30));
        star5.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\star-free-icon-font (1).png")); // NOI18N
        star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate Trip!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thank you!");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\home (1).png")); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star1ActionPerformed
        // TODO add your handling code here:
         if(star1.isSelected()){
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
        }
    }//GEN-LAST:event_star1ActionPerformed

    private void star2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star2ActionPerformed
        // TODO add your handling code here:
        if(star2.isSelected()){
            star1.setSelected(true);
            
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
        }else{
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
        }
    }//GEN-LAST:event_star2ActionPerformed

    private void star3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star3ActionPerformed
        // TODO add your handling code here:
         if(star3.isSelected()){
            star1.setSelected(true);
            star2.setSelected(true);
            
            star4.setSelected(false);
            star5.setSelected(false);
        }else{
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
        }
    }//GEN-LAST:event_star3ActionPerformed

    private void star4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star4ActionPerformed
        // TODO add your handling code here:
         if(star4.isSelected()){
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            
            star5.setSelected(false);
        }else{
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
        }
    }//GEN-LAST:event_star4ActionPerformed

    private void star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star5ActionPerformed
        // TODO add your handling code here:
        if(star5.isSelected()){
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(true);
        }else{
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
        }
    }//GEN-LAST:event_star5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            new TaxiApp().setVisible(true);
            this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finished.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finished.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finished.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finished.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finished().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox star1;
    private javax.swing.JCheckBox star2;
    private javax.swing.JCheckBox star3;
    private javax.swing.JCheckBox star4;
    private javax.swing.JCheckBox star5;
    // End of variables declaration//GEN-END:variables
}
